# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be0207c6591cef0ac20887b5d78f70d5"
name = "contifico"
handle = "contifico"
application_url = "https://instructions-higher-rca-issues.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-67ce964c.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://instructions-higher-rca-issues.trycloudflare.com/auth/callback",
  "https://instructions-higher-rca-issues.trycloudflare.com/auth/shopify/callback",
  "https://instructions-higher-rca-issues.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
