// Generated by https://quicktype.io

export interface Category {
    padre_id:          null;
    cuenta_compra:     null;
    cuenta_venta:      string;
    tipo_producto:     null;
    para_supereasy:    boolean;
    para_comisariato:  boolean;
    agrupar:           boolean;
    nombre:            string;
    id:                string;
    cuenta_inventario: null;
}