// Generated by https://quicktype.io

export interface Cellar {
    venta:      boolean;
    produccion: boolean;
    compra:     boolean;
    nombre:     string;
    codigo:     string;
    id:         string;
}