// Generated by https://quicktype.io

export interface CostCenter {
    tipo:     string;
    padre_id: null;
    nombre:   string;
    codigo:   string;
    estado:   string;
}


// Generated by https://quicktype.io

export interface CostCenterResponse {
    tipo:     string;
    padre_id: null | string;
    nombre:   string;
    codigo:   string;
    estado:   string;
    id:       string;
}