// Generated by https://quicktype.io

export interface Document {
    pos:            string;
    fecha_emision:  string;
    tipo_documento: string;
    documento?:      string;
    estado:         string;
    autorizacion?:   string;
    caja_id?:        null;
    cliente:        Cliente;
    vendedor?:       Cliente;
    descripcion:    string;
    subtotal_0:     number;
    subtotal_12:    number;
    iva:            number;
    ice?:            number;
    servicio?:       number;
    total:          number;
    adicional1?:     string;
    adicional2?:     string;
    detalles:       Detalle[];
    cobros?:         Cobro[];
}

export interface Cliente {
    ruc?:           string;
    cedula:        string;
    razon_social:  string;
    telefonos:     string;
    direccion:     string;
    tipo:          string;
    email:         string;
    es_extranjero: boolean;
}

export interface Cobro {
    forma_cobro:   string;
    monto:         number;
    numero_cheque: string;
    tipo_ping:     string;
}

export interface Detalle {
    producto_id:          string;
    cantidad:             number;
    precio:               number;
    porcentaje_iva:       number;
    porcentaje_descuento: number;
    base_cero:            number;
    base_gravable:        number;
    base_no_gravable:     number;
    porcentaje_ice?:      number;
    valor_ice?:           null;
}
