// Generated by https://quicktype.io

export interface Guide {
    cedula_chofer:       null;
    transportista_id:    string;
    fecha_emision:       string;
    electronico:         boolean;
    autorizacion:        string;
    nombre_chofer:       null;
    numero_documento:    string;
    fecha_fin:           string;
    pos:                 null;
    bodega_id:           string;
    id:                  string;
    nombre_despachador:  null;
    fecha_inicio:        string;
    ordencompraventa_id: null;
    descripcion:         string;
    direccion_partida:   string;
    estado:              string;
    placa:               string;
    adicional1:          string;
    adicional2:          null;
    destinatario:        Destinatario;
}

export interface Destinatario {
    documento_id:    string;
    codigo_destino:  string;
    direccion:       string;
    ruta:            string;
    destinatario_id: string;
    motivo:          string;
    detalle:         Detalle[];
}

export interface Detalle {
    cantidad:         string;
    serie:            null;
    producto_id:      string;
    fecha_expiracion: null;
    nombre_manual:    string;
    lote:             null;
}
