// Generated by https://quicktype.io

export interface Item {
    id:                 string;
    name:               string;
    sku:                string;
    currentQuantity:    number;
    quantity:           number;
    originalTotalSet:   Set;
    discountedTotalSet: Set;
    totalDiscountSet:   Set;
    taxLines:           TaxLine[];
    product:            totalInventory
  }
  
  export interface Set {
    shopMoney: ShopMoney;
  }
  
  export interface ShopMoney {
    amount: string;
  }
  
  export interface TaxLine {
    priceSet:       Set;
    rate:           number;
    ratePercentage: number;
    title:          string;
  }

  export interface totalInventory {
    totalInventory: number;
  }
  