// Generated by https://quicktype.io

export interface Movement {
    codigo:            string;
    bodega_id:         string;
    tipo:              string;
    fecha:             string;
    generar_asiento:   boolean;
    pos:               null;
    detalles:          Detalle[];
    maneja_venta:      null;
    descripcion:       string;
    total:             string;
    estado:            string;
    id:                string;
    bodega_destino_id: null;
    codigo_interno:    null;
}

export interface Detalle {
    serie:       null;
    producto_id: string;
    edicion:     null;
    precio:      string;
    cantidad:    string;
}