// Generated by https://quicktype.io

export interface Person {
    tipo:                 string;
    personaasociada_id?:   string;
    nombre_comercial?:     null;
    telefonos:            string | null;
    ruc?:                  string;
    razon_social:         string;
    direccion:            string;
    es_extranjero?:        boolean;
    porcentaje_descuento?: string;
    origen?:               null;
    es_cliente:           boolean;
    id?:                   null;
    es_empleado?:          boolean;
    email:                string;
    cedula:               string;
    placa?:                string;
    es_vendedor:          boolean;
    es_proveedor?:         boolean;
    adicional1_cliente?:   null;
    adicional2_cliente?:   null;
    adicional4_cliente?:   null;
    adicional1_proveedor?: null;
    adicional2_proveedor?: null;
    adicional3_proveedor?: null;
    adicional4_proveedor?: null;
}