// Generated by https://quicktype.io

export interface Product {
    porcentaje_iva?:           number;
    costo_maximo?:             null;
    descripcion_departamento?: null;
    imagen?:                   string;
    minimo:                   string;
    para_comisariato?:         boolean;
    indicador_peso?:           null;
    descripcion?:              string;
    generacion_automatica?:    boolean;
    cuenta_costo_id?:          null;
    pvp2?:                     string;
    tipo?:                     string;
    fecha_creacion?:           string;
    id?:                       string;
    tipo_producto?:            string;
    pvp3?:                     string;
    codigo_proveedor?:         string;
    pvp1:                     string;
    descripcion_familia?:      null;
    id_integracion_proveedor?: null;
    para_supereasy?:           boolean;
    nombre:                   string;
    codigo_sap?:               string;
    descripcion_jerarquia?:    null;
    pvp_manual?:               boolean;
    codigo_barra?:             string;
    pvp_comisariato?:          string;
    pvp4?:                     string;
    cuenta_venta_id?:          string;
    categoria_id?:             string;
    peso_hasta?:               null;
    pvp_peso?:                 null;
    jerarquia?:                null;
    departamento?:             null;
    para_pos?:                 boolean;
    familia?:                  null;
    marca_id?:                 null;
    marca_nombre?:             null;
    estado:                   string;
    categoria_comisariato_id?: null;
    cuenta_compra_id?:         null;
    personalizado1?:           null;
    peso_desde?:               null;
    personalizado2?:           null;
    codigo:                   string;
    nombre_producto_base?:     null;
    pvp_supereasy?:            string;
    variantes?:                null;
    producto_base_id?:         null;
    detalle_variantes?:        DetalleVariante[];
    lead_time?:                null;
    cantidad_stock?:           string;
}

export interface DetalleVariante {
    valor_id:    null;
    variante_id: string;
}

export interface Stock {
    bodega_nombre: string;
    bodega_id:     string;
    cantidad:      number;
}