// Generated by https://quicktype.io

export interface Variant {
    nombre:  string;
    id:      string;
    valores: Valore[];
}

export interface Valore {
    id:    string;
    valor: string;
}

